# ---------- Etapa 1: Build ----------
FROM node:18 AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos del proyecto
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar todo el código del proyecto
COPY . .

# Generar la versión de producción
RUN npm run build


# ---------- Etapa 2: Servidor Nginx ----------
FROM nginx:alpine

# Copiar los archivos estáticos generados al directorio de Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Exponer el puerto
EXPOSE 80

# Comando por defecto
CMD ["nginx", "-g", "daemon off;"]
